test_that("multiplication works", {
  seurat_object <- readRDS('D:\\GIBH\\IReNA2 R package\\IReNA-test-data\\IReNA-test-data\\scRNA-seq\\seurat_object.rds')
  monocle_object <- readRDS('D:\\GIBH\\IReNA2 R package\\GReNA\\monocle_object.rds')
  seurat_with_time <- add_pseudotime_DEG_filter(seurat_object, monocle_object,DEG = FALSE,normlize1 = F)
  expression_profile <- get_SmoothByBin_PseudotimeExp(seurat_with_time)
  expression_profile_filter <- fileter_expression_profile(expression_profile, FC=0.01)
  clustering <- clustering_Kmeans(expression_profile_filter, K1=4)
  col1 <- c('#67C1E3','#EF9951','#00BFC4','#AEC7E8','#C067A9','#E56145','#2F4F4F')
  plot_kmeans_pheatmap(clustering, ModuleColor1 = col1)
  Kmeans_clustering_ENS <- add_ENSID(clustering, Spec1='Hs')
  expect_equal(nrow(Kmeans_clustering_ENS),2680)
  motif1 <- Tranfac201803_Hs_MotifTFsF
  regulatory_relationship <- get_cor (Kmeans_clustering_ENS,motif1,0.6)
  TFs_list <- get_Enriched_TFs(regulatory_relationship, Kmeans_clustering_ENS, TFFdrThr1=2)
  TFs_list <- get_regulation_of_TFs_to_modules(TFs_list, Thr=10)
  tf_network <- get_partial_regulations(TFs_list)
  expect_true(nrow(tf_network)>2000)
})
