#' Combine all footprints of motifs from motif data base
#'
#' @param motif motif file, you can choose our bulit-in motif database of 'mus musculus', 'homo sapiens', 'zebrafish' and 'chicken' by 'motif = Tranfac201803_Mm_MotifTFsF', 'motif = Tranfac201803_Hs_MotifTFsF', 'motif = Tranfac201803_Zf_MotifTFsF', 'motif = Tranfac201803_Ch_MotifTFsF' respectively, or you can upload your own motif data base, but the formata use be the same as our built-in motif database.
#' @param file1 ???
#' @param Dir character, indicating the path of Fimo consequence
#'
#' @return return combined footprints
#' @export
#'
#' @examples #File1<-read.delim('Tranfac201803_MotifPWM.txt',header = F)
#' Dir2 <- 'D:/GIBH/IReNA2 R package/IReNA2/ATAC/outputdir'
#' #combied<-combine_footprints(motif1,File1,Dir2)

combine_footprints <- function(motif, file1, Dir) {
  con1 <- motif
  con2 <- file1
  DirFile1 <- list.files(Dir)
  con3 <- read.table(paste0(Dir, DirFile1[1]), header = TRUE, sep = "\t")
  col1 <- con3[, c(3, 4, 5, 6, 8, 10, 1)]
  name1 <- c()
  for (i in 1:nrow(con2)) {
    if (grepl("^>", con2[i, ]) == TRUE) {
      acc1 <- strsplit(con2[i, ], " ")[[1]][2]
      acc2 <- substr(acc1, 3, nchar(acc1))
      name1 <- c(name1, acc2)
    }
  }
  for (i in 2:length(DirFile1)) {
    info <- file.info(paste0(FootprintsDir1, "/", File1, "_Fimo/", DirFile1[i]))
    if (info$size > 0) {
      con12 <- read.table(paste0(FootprintsDir1, "/", File1, "_Fimo/", DirFile1[i]), header = TRUE, sep = "\t")
      col2 <- con12[, c(3, 4, 5, 6, 8, 10, 1)]
      col1 <- rbind(col1, col2)
    }
  }
  name2 <- c()
  for (i in con1$ID) {
    if (i %in% name1 == FALSE) {
      acc2 <- paste(i, "do not exist")
      name2 <- c(name2, acc2)
    }
  }
  return(col1)
}

#' Overlap differential peaks and motif footprints
#'
#' @param footprints footprints file, generated by combine_footprints()
#' @param peak_bed bed format of peak, first column should be 'chr', second column should be 'start', third column should be 'end'
#'
#' @return return data.frame contain footprints that overlap peaks
#' @export
#'
#' @examples peak_bed <- get_bed(peak)
#' overlapped <- overlap_footprints_peaks(combined, peak_bed)
overlap_footprints_peaks <- function(footprints, peak_bed) {
  merged <- matrix(ncol = 10)
  for (i in 1:nrow(footprints)) {
    range1 <- as.numeric(footprints[i, 2]):as.numeric(footprints[i, 3])
    for (j in 1:nrow(peak_bed)) {
      range2 <- peak_bed[j, 2]:peak_bed[j, 3]
      if (length(intersect(range1, range2)) > 0) {
        merged <- rbind(merged, c(footprints[i, ], peak_bed[j, ]))
      }
    }
  }
  merged <- merged[-1, ]
  merged <- as.data.frame(merged)
  return(merged)
}
