#' Combine all footprints of motifs
#' @description combine all footprints related motifs which generated by fimo. Before ru
#' @param Dir character, indicating the path of all footprints related motif which generated by fimo. Folder in this path cannot contain any other irrelevant files
#'
#' @return return combined footprints
#' @export
#'
#' @examples
#' #combied<-combine_footprints(Dir2)

combine_footprints <- function(Dir) {
  DirFile1 <- list.files(Dir)
  con3 <- read.table(paste0(Dir, DirFile1[1]), header = TRUE, sep = "\t")
  col1 <- con3[, c(3, 4, 5, 6, 8, 10, 1)]
  for (i in 2:length(DirFile1)) {
    info <- file.info(paste0(Dir, DirFile1[i]))
    if (info$size > 0) {
      con12 <- read.table(paste0(Dir, DirFile1[i]), header = TRUE, sep = "\t")
      col2 <- con12[, c(3, 4, 5, 6, 8, 10, 1)]
      col1 <- rbind(col1, col2)
    }
  }
  return(col1)
}

#' Overlap differential peaks and motif footprints
#'
#' @param footprints footprints file, generated by combine_footprints()
#' @param peak_bed bed format of peak, first column should be 'chr', second column should be 'start', third column should be 'end'
#'
#' @return return data.frame contain footprints that overlap peaks
#' @export
#'
#' @examples peak_bed <- get_bed(peak)
#' overlapped <- overlap_footprints_peaks(combined, peak_bed)
overlap_footprints_peaks <- function(footprints, peak_bed) {
  merged <- matrix(ncol = 10)
  for (i in 1:nrow(footprints)) {
    range1 <- as.numeric(footprints[i, 2]):as.numeric(footprints[i, 3])
    chr <- footprints[i,1]
    for (j in 1:nrow(peak_bed[peak_bed[,1] == chr,])) {
      range2 <- peak_bed[j, 2]:peak_bed[j, 3]
      if (length(intersect(range1, range2)) > 0) {
        merged <- rbind(merged, c(footprints[i, ], peak_bed[j, ]))
      }
    }
  }
  merged <- merged[-1, ]
  merged <- as.data.frame(merged)
  return(merged)
}
