#' Tranfac201803 database of Homo sapiens
#' @format contain motifs and its corresponding genes
"Tranfac201803_Hs_MotifTFsF"

#' Tranfac201803 database of chicken
#' @format contain motifs and its corresponding genes
"Tranfac201803_Mm_MotifTFsF"

#' Tranfac201803 database of Mus musculus
#' @format contain motifs and its corresponding genes
"Tranfac201803_Zf_MotifTFsF"

#' Tranfac201803 database of Chicken
#' @format contain motifs and its corresponding genes
"Tranfac201803_Ch_MotifTFsF"

#' data for test
#' @format generated by dnase2tf with fdr=0.05
"fdr005"

#' data for test
#' @format peaks file
"peak"

#' data for test
#' @format combined footprints
"combined"

#' data for test
#' @format a list contain 2 processed wig file
"wig_list"

#' data for test
#' @format combined footprints
"Candid"

#' data for test
#' @format expression profile, first column is ENSEMBLE ID, second column is Symbol
"MmscRNA_PHx_Exp_NewF"
