#' Title
#'
#' @param motif motif file
#' @param Dir motif directory contain motif files generated by Fimo
#'
#' @return print motif which do not include in the file
#' @export
#'
#' @examples
motifs_check <- function(motif, Dir) {
  con1 <- motif
  DirFile1 <- list.files(Dir)
  DirFile2 <- c()
  for (i in DirFile1) {
    name1 <- as.character(strsplit(i, ".txt"))
    DirFile2 <- c(DirFile2, name1)
  }
  Filename1 <- rownames(con1)
  Errors <- c()
  for (i in Filename1) {
    if (i %in% DirFile2 == FALSE) {
      Errors <- c(Errors, paste0(i, " not included"))
    }
  }
  print(Errors)
}
