#' wig track
#' @description Function to get cuts of each position in footprints
#' @param bamfilepath character, indicating the path of bam file
#' @param bedfile bed file of footprints, generated by get_peaks_genes()
#' @param index logical, indicating whether to index the bam file. If bam
#' file do not have a matched bai file, this parameter should be TRUE
#' @importFrom Rsamtools PileupParam
#' @importFrom Rsamtools pileup
#' @importFrom Rsamtools indexBam
#' @return return formated wig file
#' @export
#'
#' @examples load(system.file("extdata", "list1.rda", package = "IReNA"))
#' load(system.file("extdata", "test_clustering.rda", package = "IReNA"))
#' bamfilepath1<-'mmATACCtrW00R1_CuFiQ10No_sorted.bam'
#' bamfilepath2<-'mmATACCtrW00R2_CuFiQ10No_sorted.bam'
#' test_clustering <- add_ENSID(test_clustering, Spec1 = "Hs")
#' list2<-get_related_peaks(list1,test_clustering)
#' #cuts1<-wig_track(bamfilepath = bamfilepath1,bedfile = list2[[2]])
#' #cuts2<-wig_track(bamfilepath = bamfilepath2,bedfile = list2[[2]])
#' #wig_list<-list(cuts1,cuts2)
wig_track <- function(bamfilepath, bedfile, index = FALSE) {
  bed <- bedfile
  p_param <- Rsamtools::PileupParam(min_base_quality = 10L)
  if (index == TRUE) {
    Rsamtools::indexBam(bamfilepath)
  }
  res <- Rsamtools::pileup(bamfilepath, pileupParam = p_param)
  a1 <- res$pos[duplicated(res$pos)]
  a1 <- a1[!duplicated(a1)]
  for (i in a1) {
    depth <- sum(res[res$pos==i,5])
    res[res$pos==i,][1,5] <- depth
  }
  res <- res[!duplicated(res[,2]),]
  pos1 <- res$pos
  range <- c(bed[1, 3]:bed[nrow(bed), 3])
  bed_cuts <- c()
  for (i in 1:nrow(bed)) {
    seq1 <- c(bed[i, 2]:bed[i, 3])
    pos2 <- res[res$seqnames == bed[i,1],]
    pos3 <- res[res$pos %in% seq1, ]
    if (nrow(pos3) == 0) {
      cuts <- paste0(bed[i, 1], "\t", bed[i, 2], "\t", bed[i, 3], sep = "\t")
      print(paste0("No position appear in line", i, " of bedfile"))
      cuts <- paste0(cuts, paste0(rep(0, length(seq1)), collapse = "\t"))
      bed_cuts <- c(bed_cuts, cuts)
    } else {
      cuts <- c(bed[i, 1], bed[i, 2], bed[i, 3])
      for (j in 1:(length(seq1) - 1)) {
        if (seq1[j] %in% pos3$pos) {
          if (seq1[j + 1] %in% pos3$pos) {
            cuts <- c(cuts, abs(pos3[pos3$pos == seq1[j], ]$count - pos3[pos3$pos == seq1[j + 1], ]$count))
          } else{cuts <- c(cuts, pos3[pos3$pos == seq1[j], ]$count)}
        } else {
          cuts <- c(cuts, 0)
        }
        cuts <- paste0(cuts, collapse = "\t")
      }
      bed_cuts <- c(bed_cuts, cuts)
    }
  }
  bed_cuts <- as.data.frame(bed_cuts)
  return(bed_cuts)
}
